vim.keymap.set("n", "<leader>w", ":w<CR>", { desc = "Save Buffer" })
vim.keymap.set("n", "<leader>wn", function()
  vim.cmd("enew")
end, { desc = "New Buffer" })
vim.keymap.set({ "n", "v" }, "<C-a>", "<Esc>ggVG", { desc = "Select All" })
vim.keymap.set("n", "<leader>wh", "<C-w>h", { desc = "Go to left window" })
vim.keymap.set("n", "<leader>wj", "<C-w>j", { desc = "Go to lower window" })
vim.keymap.set("n", "<leader>wk", "<C-w>k", { desc = "Go to upper window" })
vim.keymap.set("n", "<leader>wl", "<C-w>l", { desc = "Go to right window" })
vim.keymap.set("n", "<leader>w<Left>", "<C-w>h", { desc = "Go to left window" })
vim.keymap.set("n", "<leader>w<Down>", "<C-w>j", { desc = "Go to lower window" })
vim.keymap.set("n", "<leader>w<Up>", "<C-w>k", { desc = "Go to upper window" })
vim.keymap.set("n", "<leader>w<Right>", "<C-w>l", { desc = "Go to right window" })
vim.keymap.set("n", "<leader>ws", ":split<CR>", { desc = "Split window below" })
vim.keymap.set("n", "<leader>wv", ":vsplit<CR>", { desc = "Split window right" })
vim.keymap.set("n", "<leader>wo", ":only<CR>", { desc = "Close other windows" })
vim.keymap.set("n", "<leader>wc", ":close<CR>", { desc = "Close current window" })
